version: '3.8'

services:
  # Banco de dados MySQL
  mysql:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: main_db
      MYSQL_USER: username
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Serviço de Login
  login-service:
    build:
      context: ./microservices/login-service
    container_name: login_service
    environment:
      - DATABASE_URL=mysql://username:userpassword@mysql:3306/login_service_db
    ports:
      - "3001:3001"
    depends_on:
      - mysql

  # Serviço de Pedido
  order-service:
    build:
      context: ./microservices/order-service
    container_name: order_service
    environment:
      - DATABASE_URL=mysql://username:userpassword@mysql:3306/order_service_db
    ports:
      - "3002:3002"
    depends_on:
      - mysql

  # Serviço de Produto
  product-service:
    build:
      context: ./microservices/product-service
    container_name: product_service
    environment:
      - DATABASE_URL=mysql://username:userpassword@mysql:3306/product_service_db
    ports:
      - "3003:3003"
    depends_on:
      - mysql

volumes:
  mysql_data:
